// // <auto-generated />
// using System;
// using DataAccess.Context;
// using Microsoft.EntityFrameworkCore;
// using Microsoft.EntityFrameworkCore.Infrastructure;
// using Microsoft.EntityFrameworkCore.Metadata;
// using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

// #nullable disable

// namespace DataAccess.Migrations
// {
//     [DbContext(typeof(HotelBookingContext))]
//     partial class HotelBookingContextModelSnapshot : ModelSnapshot
//     {
//         protected override void BuildModel(ModelBuilder modelBuilder)
//         {
// #pragma warning disable 612, 618
//             modelBuilder
//                 .HasAnnotation("ProductVersion", "10.0.2")
//                 .HasAnnotation("Relational:MaxIdentifierLength", 128);

//             //SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//             modelBuilder.Entity("DataAccess.Models.Amenity", b =>
//                 {
//                     b.Property<int>("AmenityId")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     //SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityId"));

//                     b.Property<DateTime>("CreatedDate")
//                         /*.HasColumnType("datetime2")*/;

//                     b.Property<string>("Description")
//                         .HasMaxLength(255)
//                         /*.HasColumnType("nvarchar(255)")*/;

//                     b.Property<string>("Icon")
//                         .HasMaxLength(50)
//                         /*.HasColumnType("nvarchar(50)")*/;

//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasMaxLength(100)
//                         /*.HasColumnType("nvarchar(100)")*/;

//                     b.HasKey("AmenityId");

//                     b.ToTable("Amenities");

//                     b.HasData(
//                         new
//                         {
//                             AmenityId = 1,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Free high-speed WiFi",
//                             Icon = "wifi",
//                             Name = "WiFi"
//                         },
//                         new
//                         {
//                             AmenityId = 2,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Climate control",
//                             Icon = "snowflake",
//                             Name = "Air Conditioning"
//                         },
//                         new
//                         {
//                             AmenityId = 3,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Flat-screen TV",
//                             Icon = "tv",
//                             Name = "TV"
//                         },
//                         new
//                         {
//                             AmenityId = 4,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "In-room mini bar",
//                             Icon = "glass-martini",
//                             Name = "Mini Bar"
//                         },
//                         new
//                         {
//                             AmenityId = 5,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "In-room safe",
//                             Icon = "lock",
//                             Name = "Safe"
//                         },
//                         new
//                         {
//                             AmenityId = 6,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Private bathroom",
//                             Icon = "bath",
//                             Name = "Bathroom"
//                         },
//                         new
//                         {
//                             AmenityId = 7,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Private balcony",
//                             Icon = "door-open",
//                             Name = "Balcony"
//                         },
//                         new
//                         {
//                             AmenityId = 8,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Ocean view",
//                             Icon = "water",
//                             Name = "Sea View"
//                         });
//                 });

//             modelBuilder.Entity("DataAccess.Models.Booking", b =>
//                 {
//                     b.Property<int>("BookingId")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     //SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

//                     b.Property<DateTime>("CheckInDate")
//                         /*.HasColumnType("datetime2")*/;

//                     b.Property<DateTime>("CheckOutDate")
//                         /*.HasColumnType("datetime2")*/;

//                     b.Property<DateTime>("CreatedDate")
//                         /*.HasColumnType("datetime2")*/;

//                     b.Property<int>("GuestCount")
//                         .HasColumnType("int");

//                     b.Property<int>("RoomId")
//                         .HasColumnType("int");

//                     b.Property<string>("SpecialRequests")
//                         /*.HasColumnType("nvarchar(max)")*/;

//                     b.Property<string>("Status")
//                         .IsRequired()
//                         .ValueGeneratedOnAdd()
//                         .HasMaxLength(20)
//                         /*.HasColumnType("nvarchar(20)")*/
//                         .HasDefaultValue("Pending");

//                     b.Property<decimal>("TotalPrice")
//                         .HasPrecision(10, 2)
//                         .HasColumnType("decimal(10,2)");

//                     b.Property<DateTime?>("UpdatedDate")
//                         /*.HasColumnType("datetime2")*/;

//                     b.Property<int>("UserId")
//                         .HasColumnType("int");

//                     b.HasKey("BookingId");

//                     b.HasIndex("CheckInDate");

//                     b.HasIndex("CheckOutDate");

//                     b.HasIndex("RoomId");

//                     b.HasIndex("UserId");

//                     b.ToTable("Bookings");
//                 });

//             modelBuilder.Entity("DataAccess.Models.Hotel", b =>
//                 {
//                     b.Property<int>("HotelId")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     //SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"));

//                     b.Property<string>("Address")
//                         .HasMaxLength(255)
//                         /*.HasColumnType("nvarchar(255)")*/;

//                     b.Property<string>("City")
//                         .HasMaxLength(100)
//                         /*.HasColumnType("nvarchar(100)")*/;

//                     b.Property<string>("Country")
//                         .HasMaxLength(100)
//                         /*.HasColumnType("nvarchar(100)")*/;

//                     b.Property<DateTime>("CreatedDate")
//                         /*.HasColumnType("datetime2")*/;

//                     b.Property<string>("Description")
//                         /*.HasColumnType("nvarchar(max)")*/;

//                     b.Property<string>("ImageUrl")
//                         /*.HasColumnType("nvarchar(max)")*/;

//                     b.Property<bool>("IsActive")
//                         /*.HasColumnType("bit")*/;

//                     b.Property<decimal?>("Latitude")
//                         .HasPrecision(10, 7)
//                         .HasColumnType("decimal(10,7)");

//                     b.Property<decimal?>("Longitude")
//                         .HasPrecision(10, 7)
//                         .HasColumnType("decimal(10,7)");

//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasMaxLength(200)
//                         /*.HasColumnType("nvarchar(200)")*/;

//                     b.Property<string>("Phone")
//                         .HasMaxLength(20)
//                         /*.HasColumnType("nvarchar(20)")*/;

//                     b.Property<decimal>("StarRating")
//                         .HasPrecision(2, 1)
//                         .HasColumnType("decimal(2,1)");

//                     b.Property<DateTime?>("UpdatedDate")
//                         /*.HasColumnType("datetime2")*/;

//                     b.Property<string>("Website")
//                         .HasMaxLength(200)
//                         /*.HasColumnType("nvarchar(200)")*/;

//                     b.HasKey("HotelId");

//                     b.ToTable("Hotels");

//                     b.HasData(
//                         new
//                         {
//                             HotelId = 1,
//                             Address = "123 Nguyen Hue Street",
//                             City = "Ho Chi Minh",
//                             Country = "Vietnam",
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "A luxurious 5-star hotel in the heart of the city with stunning views and world-class amenities.",
//                             IsActive = true,
//                             Name = "Grand Luxury Hotel",
//                             Phone = "028-1234-5678",
//                             StarRating = 5.0m,
//                             Website = "https://grandluxury.com"
//                         },
//                         new
//                         {
//                             HotelId = 2,
//                             Address = "456 Tran Phu Street",
//                             City = "Nha Trang",
//                             Country = "Vietnam",
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Beautiful beachfront resort with private beach access and spa facilities.",
//                             IsActive = true,
//                             Name = "Beach Paradise Resort",
//                             Phone = "0258-987-6543",
//                             StarRating = 4.5m,
//                             Website = "https://beachparadise.com"
//                         },
//                         new
//                         {
//                             HotelId = 3,
//                             Address = "789 Hoang Dieu Street",
//                             City = "Da Lat",
//                             Country = "Vietnam",
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Charming mountain lodge surrounded by pine forests and beautiful gardens.",
//                             IsActive = true,
//                             Name = "Mountain View Lodge",
//                             Phone = "0263-111-2222",
//                             StarRating = 4.0m,
//                             Website = "https://mountainview.com"
//                         });
//                 });

//             modelBuilder.Entity("DataAccess.Models.Payment", b =>
//                 {
//                     b.Property<int>("PaymentId")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     //SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

//                     b.Property<decimal>("Amount")
//                         .HasPrecision(10, 2)
//                         .HasColumnType("decimal(10,2)");

//                     b.Property<int>("BookingId")
//                         .HasColumnType("int");

//                     b.Property<DateTime>("CreatedDate")
//                         /*.HasColumnType("datetime2")*/;

//                     b.Property<DateTime?>("PaymentDate")
//                         /*.HasColumnType("datetime2")*/;

//                     b.Property<string>("PaymentMethod")
//                         .HasMaxLength(50)
//                         /*.HasColumnType("nvarchar(50)")*/;

//                     b.Property<string>("Status")
//                         .IsRequired()
//                         .ValueGeneratedOnAdd()
//                         .HasMaxLength(20)
//                         /*.HasColumnType("nvarchar(20)")*/
//                         .HasDefaultValue("Pending");

//                     b.Property<string>("TransactionId")
//                         .HasMaxLength(100)
//                         /*.HasColumnType("nvarchar(100)")*/;

//                     b.HasKey("PaymentId");

//                     b.HasIndex("BookingId")
//                         .IsUnique();

//                     b.ToTable("Payments");
//                 });

//             modelBuilder.Entity("DataAccess.Models.Review", b =>
//                 {
//                     b.Property<int>("ReviewId")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     //SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

//                     b.Property<int>("BookingId")
//                         .HasColumnType("int");

//                     b.Property<string>("Comment")
//                         /*.HasColumnType("nvarchar(max)")*/;

//                     b.Property<DateTime>("CreatedDate")
//                         /*.HasColumnType("datetime2")*/;

//                     b.Property<int>("HotelId")
//                         .HasColumnType("int");

//                     b.Property<bool>("IsApproved")
//                         /*.HasColumnType("bit")*/;

//                     b.Property<int>("Rating")
//                         .HasColumnType("int");

//                     b.Property<string>("Title")
//                         /*.HasColumnType("nvarchar(max)")*/;

//                     b.Property<DateTime?>("UpdatedDate")
//                         /*.HasColumnType("datetime2")*/;

//                     b.Property<int>("UserId")
//                         .HasColumnType("int");

//                     b.HasKey("ReviewId");

//                     b.HasIndex("BookingId")
//                         .IsUnique();

//                     b.HasIndex("HotelId");

//                     b.HasIndex("UserId");

//                     b.ToTable("Reviews");
//                 });

//             modelBuilder.Entity("DataAccess.Models.Room", b =>
//                 {
//                     b.Property<int>("RoomId")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     //SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

//                     b.Property<DateTime>("CreatedDate")
//                         /*.HasColumnType("datetime2")*/;

//                     b.Property<int>("Floor")
//                         .HasColumnType("int");

//                     b.Property<string>("RoomNumber")
//                         .IsRequired()
//                         .HasMaxLength(50)
//                         /*.HasColumnType("nvarchar(50)")*/;

//                     b.Property<int>("RoomTypeId")
//                         .HasColumnType("int");

//                     b.Property<string>("Status")
//                         .IsRequired()
//                         .ValueGeneratedOnAdd()
//                         .HasMaxLength(20)
//                         /*.HasColumnType("nvarchar(20)")*/
//                         .HasDefaultValue("Available");

//                     b.Property<DateTime?>("UpdatedDate")
//                         /*.HasColumnType("datetime2")*/;

//                     b.HasKey("RoomId");

//                     b.HasIndex("RoomNumber")
//                         .IsUnique();

//                     b.HasIndex("RoomTypeId");

//                     b.ToTable("Rooms");

//                     b.HasData(
//                         new
//                         {
//                             RoomId = 1,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Floor = 1,
//                             RoomNumber = "101",
//                             RoomTypeId = 1,
//                             Status = "Available"
//                         },
//                         new
//                         {
//                             RoomId = 2,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Floor = 1,
//                             RoomNumber = "102",
//                             RoomTypeId = 1,
//                             Status = "Available"
//                         },
//                         new
//                         {
//                             RoomId = 3,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Floor = 2,
//                             RoomNumber = "201",
//                             RoomTypeId = 2,
//                             Status = "Available"
//                         },
//                         new
//                         {
//                             RoomId = 4,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Floor = 2,
//                             RoomNumber = "202",
//                             RoomTypeId = 2,
//                             Status = "Available"
//                         },
//                         new
//                         {
//                             RoomId = 5,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Floor = 3,
//                             RoomNumber = "301",
//                             RoomTypeId = 3,
//                             Status = "Available"
//                         },
//                         new
//                         {
//                             RoomId = 6,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Floor = 1,
//                             RoomNumber = "A101",
//                             RoomTypeId = 4,
//                             Status = "Available"
//                         },
//                         new
//                         {
//                             RoomId = 7,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Floor = 1,
//                             RoomNumber = "A102",
//                             RoomTypeId = 4,
//                             Status = "Available"
//                         },
//                         new
//                         {
//                             RoomId = 8,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Floor = 2,
//                             RoomNumber = "B201",
//                             RoomTypeId = 5,
//                             Status = "Available"
//                         },
//                         new
//                         {
//                             RoomId = 9,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Floor = 2,
//                             RoomNumber = "B202",
//                             RoomTypeId = 5,
//                             Status = "Available"
//                         },
//                         new
//                         {
//                             RoomId = 10,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Floor = 1,
//                             RoomNumber = "V01",
//                             RoomTypeId = 6,
//                             Status = "Available"
//                         },
//                         new
//                         {
//                             RoomId = 11,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Floor = 1,
//                             RoomNumber = "M101",
//                             RoomTypeId = 7,
//                             Status = "Available"
//                         },
//                         new
//                         {
//                             RoomId = 12,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Floor = 1,
//                             RoomNumber = "M102",
//                             RoomTypeId = 7,
//                             Status = "Available"
//                         },
//                         new
//                         {
//                             RoomId = 13,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Floor = 2,
//                             RoomNumber = "M201",
//                             RoomTypeId = 8,
//                             Status = "Available"
//                         });
//                 });

//             modelBuilder.Entity("DataAccess.Models.RoomAmenity", b =>
//                 {
//                     b.Property<int>("RoomId")
//                         .HasColumnType("int");

//                     b.Property<int>("AmenityId")
//                         .HasColumnType("int");

//                     b.HasKey("RoomId", "AmenityId");

//                     b.HasIndex("AmenityId");

//                     b.ToTable("RoomAmenities");

//                     b.HasData(
//                         new
//                         {
//                             RoomId = 1,
//                             AmenityId = 1
//                         },
//                         new
//                         {
//                             RoomId = 1,
//                             AmenityId = 2
//                         },
//                         new
//                         {
//                             RoomId = 1,
//                             AmenityId = 3
//                         },
//                         new
//                         {
//                             RoomId = 2,
//                             AmenityId = 1
//                         },
//                         new
//                         {
//                             RoomId = 2,
//                             AmenityId = 2
//                         },
//                         new
//                         {
//                             RoomId = 2,
//                             AmenityId = 3
//                         },
//                         new
//                         {
//                             RoomId = 3,
//                             AmenityId = 1
//                         },
//                         new
//                         {
//                             RoomId = 3,
//                             AmenityId = 2
//                         },
//                         new
//                         {
//                             RoomId = 3,
//                             AmenityId = 3
//                         },
//                         new
//                         {
//                             RoomId = 3,
//                             AmenityId = 4
//                         },
//                         new
//                         {
//                             RoomId = 3,
//                             AmenityId = 5
//                         },
//                         new
//                         {
//                             RoomId = 5,
//                             AmenityId = 1
//                         },
//                         new
//                         {
//                             RoomId = 5,
//                             AmenityId = 2
//                         },
//                         new
//                         {
//                             RoomId = 5,
//                             AmenityId = 3
//                         },
//                         new
//                         {
//                             RoomId = 5,
//                             AmenityId = 4
//                         },
//                         new
//                         {
//                             RoomId = 5,
//                             AmenityId = 5
//                         },
//                         new
//                         {
//                             RoomId = 5,
//                             AmenityId = 6
//                         },
//                         new
//                         {
//                             RoomId = 5,
//                             AmenityId = 7
//                         });
//                 });

//             modelBuilder.Entity("DataAccess.Models.RoomType", b =>
//                 {
//                     b.Property<int>("RoomTypeId")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     //SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeId"));

//                     b.Property<decimal>("BasePrice")
//                         .HasPrecision(10, 2)
//                         .HasColumnType("decimal(10,2)");

//                     b.Property<int>("Capacity")
//                         .HasColumnType("int");

//                     b.Property<DateTime>("CreatedDate")
//                         /*.HasColumnType("datetime2")*/;

//                     b.Property<string>("Description")
//                         /*.HasColumnType("nvarchar(max)")*/;

//                     b.Property<int>("HotelId")
//                         .HasColumnType("int");

//                     b.Property<string>("ImageUrl")
//                         /*.HasColumnType("nvarchar(max)")*/;

//                     b.Property<string>("Name")
//                         .IsRequired()
//                         .HasMaxLength(100)
//                         /*.HasColumnType("nvarchar(100)")*/;

//                     b.Property<DateTime?>("UpdatedDate")
//                         /*.HasColumnType("datetime2")*/;

//                     b.HasKey("RoomTypeId");

//                     b.HasIndex("HotelId");

//                     b.ToTable("RoomTypes");

//                     b.HasData(
//                         new
//                         {
//                             RoomTypeId = 1,
//                             BasePrice = 1500000m,
//                             Capacity = 2,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Comfortable room with essential amenities",
//                             HotelId = 1,
//                             Name = "Standard Room"
//                         },
//                         new
//                         {
//                             RoomTypeId = 2,
//                             BasePrice = 2500000m,
//                             Capacity = 2,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Spacious room with city view",
//                             HotelId = 1,
//                             Name = "Deluxe Room"
//                         },
//                         new
//                         {
//                             RoomTypeId = 3,
//                             BasePrice = 4500000m,
//                             Capacity = 4,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Luxury suite with living area",
//                             HotelId = 1,
//                             Name = "Executive Suite"
//                         },
//                         new
//                         {
//                             RoomTypeId = 4,
//                             BasePrice = 1800000m,
//                             Capacity = 2,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Room overlooking tropical gardens",
//                             HotelId = 2,
//                             Name = "Garden View Room"
//                         },
//                         new
//                         {
//                             RoomTypeId = 5,
//                             BasePrice = 2800000m,
//                             Capacity = 2,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Room with stunning sea views",
//                             HotelId = 2,
//                             Name = "Ocean View Room"
//                         },
//                         new
//                         {
//                             RoomTypeId = 6,
//                             BasePrice = 8000000m,
//                             Capacity = 6,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Private villa with beach access",
//                             HotelId = 2,
//                             Name = "Beach Villa"
//                         },
//                         new
//                         {
//                             RoomTypeId = 7,
//                             BasePrice = 1200000m,
//                             Capacity = 2,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Warm and cozy room with mountain view",
//                             HotelId = 3,
//                             Name = "Cozy Room"
//                         },
//                         new
//                         {
//                             RoomTypeId = 8,
//                             BasePrice = 2000000m,
//                             Capacity = 4,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Description = "Large room for families",
//                             HotelId = 3,
//                             Name = "Family Room"
//                         });
//                 });

//             modelBuilder.Entity("DataAccess.Models.User", b =>
//                 {
//                     b.Property<int>("UserId")
//                         .ValueGeneratedOnAdd()
//                         .HasColumnType("int");

//                     //SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

//                     b.Property<string>("Address")
//                         .HasMaxLength(255)
//                         /*.HasColumnType("nvarchar(255)")*/;

//                     b.Property<DateTime>("CreatedDate")
//                         /*.HasColumnType("datetime2")*/;

//                     b.Property<string>("Email")
//                         .IsRequired()
//                         .HasMaxLength(100)
//                         /*.HasColumnType("nvarchar(100)")*/;

//                     b.Property<string>("FirstName")
//                         .HasMaxLength(100)
//                         /*.HasColumnType("nvarchar(100)")*/;

//                     b.Property<bool>("IsActive")
//                         /*.HasColumnType("bit")*/;

//                     b.Property<string>("LastName")
//                         .HasMaxLength(100)
//                         /*.HasColumnType("nvarchar(100)")*/;

//                     b.Property<string>("Password")
//                         .IsRequired()
//                         .HasMaxLength(100)
//                         /*.HasColumnType("nvarchar(100)")*/;

//                     b.Property<string>("PhoneNumber")
//                         .HasMaxLength(20)
//                         /*.HasColumnType("nvarchar(20)")*/;

//                     b.Property<string>("Role")
//                         .IsRequired()
//                         .ValueGeneratedOnAdd()
//                         .HasMaxLength(20)
//                         /*.HasColumnType("nvarchar(20)")*/
//                         .HasDefaultValue("Customer");

//                     b.Property<DateTime?>("UpdatedDate")
//                         /*.HasColumnType("datetime2")*/;

//                     b.HasKey("UserId");

//                     b.HasIndex("Email")
//                         .IsUnique();

//                     b.ToTable("Users");

//                     b.HasData(
//                         new
//                         {
//                             UserId = 1,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Email = "admin@hotel.com",
//                             FirstName = "Admin",
//                             IsActive = true,
//                             LastName = "System",
//                             Password = "Admin@123",
//                             PhoneNumber = "0123456789",
//                             Role = "Admin"
//                         },
//                         new
//                         {
//                             UserId = 2,
//                             CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
//                             Email = "customer@hotel.com",
//                             FirstName = "Nguyen",
//                             IsActive = true,
//                             LastName = "Van A",
//                             Password = "Customer@123",
//                             PhoneNumber = "0987654321",
//                             Role = "Customer"
//                         });
//                 });

//             modelBuilder.Entity("DataAccess.Models.Booking", b =>
//                 {
//                     b.HasOne("DataAccess.Models.Room", "Room")
//                         .WithMany("Bookings")
//                         .HasForeignKey("RoomId")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.HasOne("DataAccess.Models.User", "User")
//                         .WithMany("Bookings")
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.Navigation("Room");

//                     b.Navigation("User");
//                 });

//             modelBuilder.Entity("DataAccess.Models.Payment", b =>
//                 {
//                     b.HasOne("DataAccess.Models.Booking", "Booking")
//                         .WithOne("Payment")
//                         .HasForeignKey("DataAccess.Models.Payment", "BookingId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("Booking");
//                 });

//             modelBuilder.Entity("DataAccess.Models.Review", b =>
//                 {
//                     b.HasOne("DataAccess.Models.Booking", "Booking")
//                         .WithOne("Review")
//                         .HasForeignKey("DataAccess.Models.Review", "BookingId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.HasOne("DataAccess.Models.Hotel", "Hotel")
//                         .WithMany("Reviews")
//                         .HasForeignKey("HotelId")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.HasOne("DataAccess.Models.User", "User")
//                         .WithMany("Reviews")
//                         .HasForeignKey("UserId")
//                         .OnDelete(DeleteBehavior.Restrict)
//                         .IsRequired();

//                     b.Navigation("Booking");

//                     b.Navigation("Hotel");

//                     b.Navigation("User");
//                 });

//             modelBuilder.Entity("DataAccess.Models.Room", b =>
//                 {
//                     b.HasOne("DataAccess.Models.RoomType", "RoomType")
//                         .WithMany("Rooms")
//                         .HasForeignKey("RoomTypeId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("RoomType");
//                 });

//             modelBuilder.Entity("DataAccess.Models.RoomAmenity", b =>
//                 {
//                     b.HasOne("DataAccess.Models.Amenity", "Amenity")
//                         .WithMany("RoomAmenities")
//                         .HasForeignKey("AmenityId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.HasOne("DataAccess.Models.Room", "Room")
//                         .WithMany("RoomAmenities")
//                         .HasForeignKey("RoomId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("Amenity");

//                     b.Navigation("Room");
//                 });

//             modelBuilder.Entity("DataAccess.Models.RoomType", b =>
//                 {
//                     b.HasOne("DataAccess.Models.Hotel", "Hotel")
//                         .WithMany("RoomTypes")
//                         .HasForeignKey("HotelId")
//                         .OnDelete(DeleteBehavior.Cascade)
//                         .IsRequired();

//                     b.Navigation("Hotel");
//                 });

//             modelBuilder.Entity("DataAccess.Models.Amenity", b =>
//                 {
//                     b.Navigation("RoomAmenities");
//                 });

//             modelBuilder.Entity("DataAccess.Models.Booking", b =>
//                 {
//                     b.Navigation("Payment");

//                     b.Navigation("Review");
//                 });

//             modelBuilder.Entity("DataAccess.Models.Hotel", b =>
//                 {
//                     b.Navigation("Reviews");

//                     b.Navigation("RoomTypes");
//                 });

//             modelBuilder.Entity("DataAccess.Models.Room", b =>
//                 {
//                     b.Navigation("Bookings");

//                     b.Navigation("RoomAmenities");
//                 });

//             modelBuilder.Entity("DataAccess.Models.RoomType", b =>
//                 {
//                     b.Navigation("Rooms");
//                 });

//             modelBuilder.Entity("DataAccess.Models.User", b =>
//                 {
//                     b.Navigation("Bookings");

//                     b.Navigation("Reviews");
//                 });
// #pragma warning restore 612, 618
//         }
//     }
// }
